// require('./build/structural/adapter/main')
// require('./build/structural/bridge/main')
// require('./build/structural/composite/main')
// require('./build/structural/decorator/main')
// require('./build/structural/facade/main')
// require('./build/structural/flyweight/main')
// require('./build/structural/proxy/main')

// require('./build/creational/abstract-factory/main')
// require('./build/creational/builder/main')
// require('./build/creational/factory/main')
// require('./build/creational/prototype/main')
// require('./build/creational/singleton/main')

require('./build/behavioral/mediator/main')