// require('./build/structural/adapter/main')
// require('./build/structural/bridge/main')
// require('./build/structural/composite/main')
// require('./build/structural/decorator/main')
// require('./build/structural/facade/main')
// require('./build/structural/flyweight/main')
// require('./build/structural/proxy/main')

// require('./build/creational/abstract-factory/main')
// require('./build/creational/builder/main')
// require('./build/creational/factory/main')
// require('./build/creational/prototype/main')
// require('./build/creational/singleton/main')

// require('./build/behavioral/chain-of-responsibility/main')
// require('./build/behavioral/command/main')
// require('./build/behavioral/iterator/main')
// require('./build/behavioral/mediator/main')
// require('./build/behavioral/memento/main')
// require('./build/behavioral/observer/main')
// require('./build/behavioral/state/main')
// require('./build/behavioral/strategy/main')
// require('./build/behavioral/template/main')
// require('./build/behavioral/visitor/main')